# Generated by Django 3.0.6 on 2020-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_model',
            name='chapter',
        ),
        migrations.AddField(
            model_name='question_model',
            name='exercise',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question_model',
            name='unit_name',
            field=models.CharField(default='MATRICS', max_length=200),
            preserve_default=False,
        ),
    ]
