# Generated by Django 3.0.6 on 2020-08-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_question_model_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_model',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
